image: "python:3.8"

stages:
  - Testing
  - Deployment

test:
  stage: Testing
  before_script:
    - make init
  script:
    - make test
    - poetry run python -m flake8 .

deploy:
  stage: Deployment
  before_script:
    - pip install 'twine>=1.5.0'
    - echo "[pypi]" >> $HOME/.pypirc
    - echo "  username = __token__" >> $HOME/.pypirc
    - echo "  password = $PYPI_TOKEN" >> $HOME/.pypirc
    - cat $HOME/.pypirc
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
