image: "python:3.7"

stages:
  - Testing
  - Deployment

test:
  stage: Testing
  before_script:
    - pip install pipenv --upgrade
    - pipenv install --dev
  script:
    - pipenv run nosetests

deploy:
  stage: Deployment
  before_script:
    - pip install 'twine>=1.5.0'
    - cat $HOME/.pypirc
    - echo "[pypi]" >> $HOME/.pypirc
    - echo "  username = __token__" >> $HOME/.pypirc
    - echo "  password = $PYPI_TOKEN" >> $HOME/.pypirc
  script:
    - python setup.py sdist bdist_wheel
    - echo 'DONE'
